# Copyright Glen Knowles 2016 - 2021.
# Distributed under the Boost Software License, Version 1.0.
version: 0.1.{build}
image: Visual Studio 2022

environment:
  matrix:
    - toolset: v143
platform:
  - x64
configuration:
  - Debug

build_script:
  - git submodule update --init
  - md build
  - cd build
  - cmake -G "Visual Studio 17 2022" -A %platform% -T %toolset% ..
  - cmake -DCMAKE_BUILD_TYPE=%configuration% .
        -DCMAKE_INSTALL_PREFIX=publish
        -DINSTALL_TOOLS:BOOL=ON
  - cmake --build . --target install --config %configuration%
  - cd publish
  - 7z a tismet-latest.zip bin
  - cd ..\..

artifacts:
  - path: build\publish\tismet-latest.zip
    name: tismet
    type: zip

test_script:
    - bin\tst all
