version: 0.1.{build}
image: Visual Studio 2017

platform:
  - x64
configuration:
  - Debug

build_script:
  - git submodule update --init --recursive

  # hack to stop sea of Xamarin (which isn't being used at all) warnings
  # during the cmake install
  - del "C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets"

  - md build
  - cd build
  - cmake -G "Visual Studio 15 2017 Win64" ..
  - cmake -DCMAKE_BUILD_TYPE=%configuration% -DCMAKE_INSTALL_PREFIX=publish .
  - cmake --build . --target install --config %configuration%
  - cd publish
  - 7z a tismet-latest.zip bin\*.exe bin\*.pdb
  - cd ..\..

test_script:

artifacts:
  - path: build\publish\tismet-latest.zip
    name: tismet
    type: zip
