version: 0.1.{build}

platform:
  - x64
configuration:
  - Debug

build:
  parallel: true
  project: tismet.sln
  verbosity: minimal

test_script:
  - lib\dim\bin\cmdline
  - lib\dim\bin\hpack
  - lib\dim\bin\http

artifacts:
  - path: bin\*.exe
  - path: bin\*.pdb

deploy:
  release: tismet-trunk
  description: tismet $(appveyor_build_version)
  provider: GitHub
  auth_token:
    secure: yheCA/FJ+f7CL84HoPf9MapOlDZQmrGyiqlwFeeIhxvdOudQisUdOyZuWfwq3lUU
  prerelease: true
  draft: true
