// carbonparseint.h
// Generated by pargen 2.2.0 at 2018-08-13T01:48:27-0700
// clang-format off
#pragma once

#include "carbonparsebaseint.h"


/****************************************************************************
*
*   CarbonParser
*
***/

class CarbonParser : public CarbonParserBase {
public:
    using CarbonParserBase::CarbonParserBase;

    bool parse (const char src[]);
    size_t errpos () const { return m_errpos; }

private:
    // Events
    bool onExpMinusEnd ();
    bool onExpNumChar (char ch);
    bool onFracNumChar (char ch);
    bool onIntMinusEnd ();
    bool onIntNumChar (char ch);
    bool onMetricEnd ();
    bool onNowEnd ();
    bool onPathStart (const char * ptr);
    bool onPathEnd (const char * eptr);
    bool onTimepointChar (char ch);

    // Data members
    size_t m_errpos{0};
};
