// carbonparseint.h
// Generated by pargen 2.1.2 at 2017-10-15T14:30:40-0700
// clang-format off
#pragma once

#include "carbonparsebaseint.h"


/****************************************************************************
*
*   CarbonParser
*
***/

class CarbonParser : public CarbonParserBase {
public:
    using CarbonParserBase::CarbonParserBase;

    bool parse (const char src[]);
    size_t errpos () const { return m_errpos; }

private:
    // Events
    bool onExpMinusEnd ();
    bool onExpNumChar (char ch);
    bool onFracNumChar (char ch);
    bool onIntMinusEnd ();
    bool onIntNumChar (char ch);
    bool onMetricEnd ();
    bool onPathStart (const char * ptr);
    bool onPathEnd (const char * eptr);
    bool onTimestampChar (char ch);

    // Data members
    size_t m_errpos{0};
};
