// carbonparseint.h
// Generated by pargen at 2017-07-15T15:45:41-0700
// clang-format off
#pragma once

#include "carbonparsebaseint.h"


/****************************************************************************
*
*   CarbonParser
*
***/

class CarbonParser : public CarbonParserBase {
public:
    using CarbonParserBase::CarbonParserBase;

    bool parse (const char src[]);
    size_t errpos () const { return m_errpos; }

private:
    // Events
    bool onStart ();
    bool onEnd ();

    bool onExpMinusEnd (const char * eptr);
    bool onExpNumChar (char ch);
    bool onFracNumChar (char ch);
    bool onIntChar (char ch);
    bool onMetricEnd (const char * eptr);
    bool onMinusEnd (const char * eptr);
    bool onPathStart (const char * ptr);
    bool onPathEnd (const char * eptr);
    bool onTimestampChar (char ch);

    // Data members
    size_t m_errpos{0};
};
