// qryparseint.h
// Generated by pargen 2.2.0 at 2018-11-16T19:55:24-0800
// clang-format off
#pragma once

#include "qryparsebaseint.h"


/****************************************************************************
*
*   QueryParser
*
***/

class QueryParser : public QueryParserBase {
public:
    using QueryParserBase::QueryParserBase;

    bool parse (const char src[]);
    size_t errpos () const { return m_errpos; }

private:
    bool stateQuery (const char *& src);
    bool stateSslSegs (const char *& src);

    // Events
    bool onArgNumEnd ();
    bool onExpMinusEnd ();
    bool onExpNumChar (char ch);
    bool onFnAbsoluteStart ();
    bool onFnAggregateStart ();
    bool onFnAliasStart ();
    bool onFnAliasSubStart ();
    bool onFnAverageAboveStart ();
    bool onFnAverageBelowStart ();
    bool onFnAverageSeriesStart ();
    bool onFnColorStart ();
    bool onFnConsolidateByStart ();
    bool onFnCountSeriesStart ();
    bool onFnCurrentAboveStart ();
    bool onFnCurrentBelowStart ();
    bool onFnDerivativeStart ();
    bool onFnDiffSeriesStart ();
    bool onFnDrawAsInfiniteStart ();
    bool onFnFilterSeriesStart ();
    bool onFnFirstSeriesStart ();
    bool onFnGroupStart ();
    bool onFnHighestStart ();
    bool onFnHighestAverageStart ();
    bool onFnHighestCurrentStart ();
    bool onFnHighestMaxStart ();
    bool onFnInvertStart ();
    bool onFnIsNonNullStart ();
    bool onFnKeepLastValueStart ();
    bool onFnLastSeriesStart ();
    bool onFnLegendValueStart ();
    bool onFnLineWidthStart ();
    bool onFnLogarithmStart ();
    bool onFnLowestStart ();
    bool onFnLowestAverageStart ();
    bool onFnLowestCurrentStart ();
    bool onFnMaxSeriesStart ();
    bool onFnMaximumAboveStart ();
    bool onFnMaximumBelowStart ();
    bool onFnMedianSeriesStart ();
    bool onFnMinSeriesStart ();
    bool onFnMinimumAboveStart ();
    bool onFnMinimumBelowStart ();
    bool onFnMovingAverageStart ();
    bool onFnMultiplySeriesStart ();
    bool onFnNonNegativeDerivativeStart ();
    bool onFnOffsetStart ();
    bool onFnPowStart ();
    bool onFnRangeSeriesStart ();
    bool onFnRemoveAboveValueStart ();
    bool onFnRemoveBelowValueStart ();
    bool onFnScaleStart ();
    bool onFnScaleToSecondsStart ();
    bool onFnSquareRootStart ();
    bool onFnStddevSeriesStart ();
    bool onFnSumSeriesStart ();
    bool onFnTimeShiftStart ();
    bool onFracNumChar (char ch);
    bool onFuncEnd ();
    bool onIntChar (char ch);
    bool onMinusEnd ();
    bool onPathStart ();
    bool onPathEnd ();
    bool onPathSegStart ();
    bool onPathSegEnd ();
    bool onSclRangeEndChar (char ch);
    bool onSclSingleChar (char ch);
    bool onSegBlotEnd ();
    bool onSegCharListEnd ();
    bool onSegLiteralStart (const char * ptr);
    bool onSegLiteralEnd (const char * eptr);
    bool onSslCommaEnd ();
    bool onSslSegsStart ();
    bool onSslSegsEnd ();
    bool onStringStart (const char * ptr);
    bool onStringEnd (const char * eptr);

    // Data members
    size_t m_errpos{0};
};
