// queryparseint.h
// Generated by pargen 2.1.3 at 2018-07-22T02:34:45-0700
// clang-format off
#pragma once

#include "queryparsebaseint.h"


/****************************************************************************
*
*   QueryParser
*
***/

class QueryParser : public QueryParserBase {
public:
    using QueryParserBase::QueryParserBase;

    bool parse (const char src[]);
    size_t errpos () const { return m_errpos; }

private:
    bool stateQuery (const char *& src);
    bool stateSslSegs (const char *& src);

    // Events
    bool onArgNumEnd ();
    bool onArgQueryStart ();
    bool onExpMinusEnd ();
    bool onExpNumChar (char ch);
    bool onFnAliasStart ();
    bool onFnAliasSubStart ();
    bool onFnAverageSeriesStart ();
    bool onFnColorStart ();
    bool onFnCountSeriesStart ();
    bool onFnDerivativeStart ();
    bool onFnDiffSeriesStart ();
    bool onFnDrawAsInfiniteStart ();
    bool onFnHighestCurrentStart ();
    bool onFnHighestMaxStart ();
    bool onFnKeepLastValueStart ();
    bool onFnLegendValueStart ();
    bool onFnLineWidthStart ();
    bool onFnMaxSeriesStart ();
    bool onFnMaximumAboveStart ();
    bool onFnMinSeriesStart ();
    bool onFnMovingAverageStart ();
    bool onFnMultiplySeriesStart ();
    bool onFnNonNegativeDerivativeStart ();
    bool onFnRemoveAboveValueStart ();
    bool onFnRemoveBelowValueStart ();
    bool onFnScaleStart ();
    bool onFnScaleToSecondsStart ();
    bool onFnStddevSeriesStart ();
    bool onFnSumSeriesStart ();
    bool onFnTimeShiftStart ();
    bool onFracNumChar (char ch);
    bool onFuncEnd ();
    bool onIntChar (char ch);
    bool onMinusEnd ();
    bool onPathStart ();
    bool onPathEnd ();
    bool onPathSegStart ();
    bool onPathSegEnd ();
    bool onSclRangeEndChar (char ch);
    bool onSclSingleChar (char ch);
    bool onSegBlotEnd ();
    bool onSegCharListEnd ();
    bool onSegLiteralStart (const char * ptr);
    bool onSegLiteralEnd (const char * eptr);
    bool onSslCommaEnd ();
    bool onSslSegsStart ();
    bool onSslSegsEnd ();
    bool onStringStart (const char * ptr);
    bool onStringEnd (const char * eptr);

    // Data members
    size_t m_errpos{0};
};
