// fnenum.h - tismet func
// Generated by genfuncs 1.0.0
// clang-format off
#pragma once


/****************************************************************************
*
*   Declarations
*
***/

namespace Eval {

namespace Function {
    enum Type : int {
        kInvalid = 0,
        kAbsolute = 1,
        kAggregate = 2,
        kAlias = 3,
        kAliasSub = 4,
        kAverageSeries = 5,
        kColor = 6,
        kConsolidateBy = 7,
        kCountSeries = 8,
        kDerivative = 9,
        kDiffSeries = 10,
        kDrawAsInfinite = 11,
        kFirstSeries = 12,
        kHighestCurrent = 13,
        kHighestMax = 14,
        kKeepLastValue = 15,
        kLastSeries = 16,
        kLegendValue = 17,
        kLineWidth = 18,
        kMaxSeries = 19,
        kMaximumAbove = 20,
        kMedianSeries = 21,
        kMinSeries = 22,
        kMovingAverage = 23,
        kMultiplySeries = 24,
        kNonNegativeDerivative = 25,
        kRangeSeries = 26,
        kRemoveAboveValue = 27,
        kRemoveBelowValue = 28,
        kScale = 29,
        kScaleToSeconds = 30,
        kStddevSeries = 31,
        kSumSeries = 32,
        kTimeShift = 33,
    };
}

namespace Aggregate {
    enum Type : int {
        kInvalid = 0,
        kAverage = 1,
        kCount = 2,
        kDiff = 3,
        kFirst = 4,
        kLast = 5,
        kMax = 6,
        kMedian = 7,
        kMin = 8,
        kMultiply = 9,
        kRange = 10,
        kStddev = 11,
        kSum = 12,
    };
}

} // namespace
