// fnenum.h - tismet func
// Generated by genfuncs 1.0.0
// clang-format off
#pragma once


/****************************************************************************
*
*   Declarations
*
***/

namespace Eval {

namespace Function {
    enum Type : int {
        kInvalid = 0,
        kAbsolute = 1,
        kAggregate = 2,
        kAlias = 3,
        kAliasSub = 4,
        kAverageSeries = 5,
        kColor = 6,
        kConsolidateBy = 7,
        kCountSeries = 8,
        kDerivative = 9,
        kDiffSeries = 10,
        kDrawAsInfinite = 11,
        kHighestCurrent = 12,
        kHighestMax = 13,
        kKeepLastValue = 14,
        kLastSeries = 15,
        kLegendValue = 16,
        kLineWidth = 17,
        kMaxSeries = 18,
        kMaximumAbove = 19,
        kMedianSeries = 20,
        kMinSeries = 21,
        kMovingAverage = 22,
        kMultiplySeries = 23,
        kNonNegativeDerivative = 24,
        kRangeSeries = 25,
        kRemoveAboveValue = 26,
        kRemoveBelowValue = 27,
        kScale = 28,
        kScaleToSeconds = 29,
        kStddevSeries = 30,
        kSumSeries = 31,
        kTimeShift = 32,
    };
}

namespace Aggregate {
    enum Type : int {
        kInvalid = 0,
        kAverage = 1,
        kCount = 2,
        kDiff = 3,
        kLast = 4,
        kMax = 5,
        kMedian = 6,
        kMin = 7,
        kMultiply = 8,
        kRange = 9,
        kStddev = 10,
        kSum = 11,
    };
}

} // namespace
