// funcenum.h - tismet func
// Generated by genfuncs 1.0.0
// clang-format off
#pragma once


/****************************************************************************
*
*   Declarations
*
***/

namespace Eval {

namespace Function {
    enum Type : int {
        kAlias = 0,
        kAliasSub = 1,
        kAverageSeries = 2,
        kColor = 3,
        kConsolidateBy = 4,
        kCountSeries = 5,
        kDerivative = 6,
        kDiffSeries = 7,
        kDrawAsInfinite = 8,
        kHighestCurrent = 9,
        kHighestMax = 10,
        kKeepLastValue = 11,
        kLegendValue = 12,
        kLineWidth = 13,
        kMaxSeries = 14,
        kMaximumAbove = 15,
        kMinSeries = 16,
        kMovingAverage = 17,
        kMultiplySeries = 18,
        kNonNegativeDerivative = 19,
        kRemoveAboveValue = 20,
        kRemoveBelowValue = 21,
        kScale = 22,
        kScaleToSeconds = 23,
        kStddevSeries = 24,
        kSumSeries = 25,
        kTimeShift = 26,
    };
}

namespace Aggregate {
    enum Type : int {
        kAverage = 0,
        kCount = 1,
        kDiff = 2,
        kLast = 3,
        kMax = 4,
        kMedian = 5,
        kMin = 6,
        kMultiply = 7,
        kRange = 8,
        kStddev = 9,
        kSum = 10,
    };
}

} // namespace
