// funcenum.h - tismet func
// Generated by genfuncs 1.0.0
// clang-format off
#pragma once


/****************************************************************************
*
*   Declarations
*
***/

namespace Eval {

namespace Function {
    enum Type : int {
        kAbsolute = 0,
        kAggregate = 1,
        kAlias = 2,
        kAliasSub = 3,
        kAverageSeries = 4,
        kColor = 5,
        kConsolidateBy = 6,
        kCountSeries = 7,
        kDerivative = 8,
        kDiffSeries = 9,
        kDrawAsInfinite = 10,
        kHighestCurrent = 11,
        kHighestMax = 12,
        kKeepLastValue = 13,
        kLastSeries = 14,
        kLegendValue = 15,
        kLineWidth = 16,
        kMaxSeries = 17,
        kMaximumAbove = 18,
        kMedianSeries = 19,
        kMinSeries = 20,
        kMovingAverage = 21,
        kMultiplySeries = 22,
        kNonNegativeDerivative = 23,
        kRangeSeries = 24,
        kRemoveAboveValue = 25,
        kRemoveBelowValue = 26,
        kScale = 27,
        kScaleToSeconds = 28,
        kStddevSeries = 29,
        kSumSeries = 30,
        kTimeShift = 31,
    };
}

namespace Aggregate {
    enum Type : int {
        kAverage = 0,
        kCount = 1,
        kDiff = 2,
        kLast = 3,
        kMax = 4,
        kMedian = 5,
        kMin = 6,
        kMultiply = 7,
        kRange = 8,
        kStddev = 9,
        kSum = 10,
    };
}

} // namespace
