# Copyright Glen Knowles 2022 - 2023.
# Distributed under the Boost Software License, Version 1.0.
#
# github-build.yml

name: build

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]
  workflow_dispatch: {}

jobs:
  build-win:
    strategy:
      matrix:
        platform: [x64]
        configuration: [Debug, Release]
        toolset: [v143]
        image: [windows-2022]
        coverage: [false]
        include:
          - platform: x64
            configuration: Debug
            toolset: v143
            image: windows-2022
            coverage: true
    runs-on: ${{matrix.image}}
    defaults:
      run:
        shell: cmd
    steps:
    - name: Setup OpenCppCoverage
      if: matrix.coverage
      working-directory: ${{github.workspace}}
      run: |
        choco install OpenCppCoverage -y
        echo "C:\Program Files\OpenCppCoverage" >> %GITHUB_PATH%

    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Build
      working-directory: ${{github.workspace}}
      run: |
        md build
        cd build
        if "${{matrix.toolset}}" == "v143" (
          set gen=Visual Studio 17 2022
        ) else (
          set gen=Visual Studio 16 2019
        )
        cmake .. -G "%gen%" -A ${{matrix.platform}} -T ${{matrix.toolset}}
        cmake . -DCMAKE_BUILD_TYPE=${{matrix.configuration}}^
          -DCMAKE_INSTALL_PREFIX=publish -DINSTALL_LIBS:BOOL=ON
        cmake --build . --target install --config ${{matrix.configuration}}
        cd publish

    - name: Test
      if: ${{ !matrix.coverage }}
      working-directory: ${{github.workspace}}
      run: |
        bin\tst all

    - name: Test Coverage
      if: matrix.coverage
      working-directory: ${{github.workspace}}
      run: |
        "C:\Program Files\OpenCppCoverage\OpenCppCoverage.exe"^
            --export_type cobertura:merged.xml^
            --modules ${{github.workspace}}^
            --sources ${{github.workspace}}^
            --excluded_sources vendor^
            --excluded_sources tests^
            --excluded_sources testlibs^
            --excluded_line_regex ".* LCOV_EXCL_LINE.*"^
            -- bin\tst all

    - name: Report Coverage
      if: matrix.coverage
      uses: codecov/codecov-action@v3
      with:
        files: merged.xml
        fail_ci_if_error: true

